version: '3'

services:

  server:
    image: nginx:alpine
    restart: always
    depends_on:
      - web
    volumes:
     - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
     - ./public:/code/public
    environment:
     - VIRTUAL_HOST={{cookiecutter.domain}}
     - LETSENCRYPT_HOST={{cookiecutter.domain}}

  web:
    build: .
    command: sh -c "/code/run.sh"
    restart: always
    env_file:
    - .env
    depends_on:
    - postgres
    volumes:
    - ./public:/code/public
    labels:
      ofelia.enabled: "true"
#      ofelia.job-exec.example_task.schedule: "@every 60s"
#      ofelia.job-exec.example_task.command: "python3 manage.py example_task"

  postgres:
    image: postgres:14-alpine
    restart: always
    env_file:
    - .env
    volumes:
    - ./dumps:/code/dumps
    - ./data/postgresql:/var/lib/postgresql/data

  ofelia:
    image: mcuadros/ofelia:latest
    depends_on:
      - web
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro