version: '3'

services:

  postgres:
    platform: linux/amd64
    image: postgres:14-alpine
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - ./dumps:/code/dumps
      - ./data/postgresql:/var/lib/postgresql/data
