version: '3'

services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./conf/nginx-proxy/vhost.d:/etc/nginx/vhost.d:ro
      - ./conf/nginx-proxy/proxy.conf:/etc/nginx/proxy.conf
      - ./data/nginx-proxy/certs:/etc/nginx/certs
      - ./data/nginx-proxy/html:/usr/share/nginx/html
    environment:
      - RESOLVERS=8.8.8.8

  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    environment:
      - DEFAULT_EMAIL={{cookiecutter.email}}
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/acme.sh
      - ./conf/nginx-proxy/vhost.d:/etc/nginx/vhost.d
      - ./data/nginx-proxy/certs:/etc/nginx/certs
      - ./data/nginx-proxy/html:/usr/share/nginx/html
    depends_on:
      - "nginx-proxy"
